export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'
export const PRODUCT_LIST_REQUIRED = 'PRODUCT_LIST_REQUIRED'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'
export const PRODUCT_DETAILS_REQUIRED = 'PRODUCT_DETAILS_REQUIRED'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'

export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED'
export const PRODUCT_DELETE_REQUIRED = 'PRODUCT_DELETE_REQUIRED'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'

export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_REQUIRE = 'PRODUCT_CREATE_REQUIRE'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_REQUIRE = 'PRODUCT_UPDATE_REQUIRE'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_REQUIRE = 'PRODUCT_CREATE_REVIEW_REQUIRE'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'
export const PRODUCT_TOP_REQUIRE = 'PRODUCT_TOP_REQUIRE'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'