export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED'
export const PRODUCT_LIST_REQUIRED = 'PRODUCT_LIST_REQUIRED'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED'
export const PRODUCT_DETAILS_REQUIRED = 'PRODUCT_DETAILS_REQUIRED'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'